version: '3'
services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  pisignage-server:
    image: pisignage/pisignage-server:latest
    restart: unless-stopped
    ports:
      - 9006:9006
    volumes:
      - media:/media
      - data:/data
    depends_on:
      - mongo

volumes:
  mongodb:
  mongodb_config:
  media:
  data:
